name: ktlint

on:
  pull_request:
    branches:
      - main
      - develop
jobs:
  ktlint:
    name: Check Code Quality
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@develop
        with:
          fetch-depth: 1

      - name: ktlint
        uses: ScaCap/action-ktlint@develop
        with:
          github_token: ${{ secrets.TOKEN }}
          reporter: github-pr-review # Change reporter
          android: true
