name: reviewdog

on: [pull_request]

env:
  GITHUB_TOKEN: ${{ secrets.TOKEN}}

jobs:
  ktlint:
    name: Check Code Quality
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@main
        with:
          fetch-depth: 1

      - name: ktlint
        uses: ScaCap/action-ktlint@master
        with:
          reporter: github-pr-review # Change reporter
          android: true